import type { ProjectContentPack } from "@/content/projects/types";

/**
 * Verified from the Jauml MultiLoader repository (LIBRARY_VERSION 2.1.1),
 * MIGRATION_GUIDE.md, CHANGELOG.md, and public CurseForge / Modrinth listings.
 * Do not invent Maven coordinates or license claims beyond what source/metadata show.
 */
export const JAUML_CONTENT: ProjectContentPack = {
  slug: "jauml",
  source: "https://github.com/MeherBenSalem/jauml (common-shared JaumlConfig.LIBRARY_VERSION=2.1.1)",
  docs: [
    {
      slug: "overview",
      title: "Overview",
      sortOrder: 0,
      content: [
        "## Jauml",
        "",
        "Jauml (Just Another Utility Minecraft Lib) is a lightweight **JSON configuration library** for Minecraft mods. Dependent mods use its Java API (`tn.naizo.jauml.api`) to load, save, validate, and migrate JSON configs under the game config directory.",
        "",
        "It does **not** add blocks, items, or world content. Players usually install it because another mod lists it as a required dependency.",
        "",
        "Current shared library version: **2.1.1** (`JaumlConfig.LIBRARY_VERSION`). NightBeam publishes Fabric, Forge, and NeoForge jars through CurseForge, Modrinth, and GitHub Releases.",
        "",
        "## Key capabilities",
        "",
        "- Open JSON configs with `JaumlConfig.open(subdirectory, fileName)`",
        "- Load, pretty-print save, and `reload()` via `ConfigFile`",
        "- Optional `JsonSchema` validation and default-template normalization",
        "- Corrupted-config recovery (rename to `*.json.bak`, recreate from defaults)",
        "- Sequential migrations with `JsonMigrator`",
        "- Compatibility checks via `JaumlConfig.isCompatible(requiredVersion)`",
        "",
        "## Links",
        "",
        "- [CurseForge](https://www.curseforge.com/minecraft/mc-mods/jauml)",
        "- [Modrinth](https://modrinth.com/mod/jauml)",
        "- [GitHub](https://github.com/MeherBenSalem/jauml)",
        "- [Migration guide](https://github.com/MeherBenSalem/jauml/blob/main/MIGRATION_GUIDE.md)",
      ].join("\n"),
    },
    {
      slug: "installation",
      title: "Installation",
      sortOrder: 1,
      content: [
        "## For players",
        "",
        "1. Install a supported Minecraft version and loader (Fabric, Forge, or NeoForge).",
        "2. Download the Jauml jar that matches your **game version and loader** from CurseForge, Modrinth, or GitHub Releases.",
        "3. Place it in the `mods` folder (or let a launcher/modpack resolve the dependency).",
        "4. Install any mods that depend on Jauml.",
        "5. Launch the game.",
        "",
        "Installers usually pull Jauml automatically when a dependent mod requires it.",
        "",
        "## For server owners",
        "",
        "1. Match the server Minecraft version and loader to the pack/clients.",
        "2. Add the same Jauml jar to the server `mods` folder.",
        "3. Keep Jauml aligned on client and server when dependent mods need the library on both sides.",
        "4. Prefer **2.1.1+** over older **1.3.0** jars (legacy mixin stub crashes — see Troubleshooting).",
        "",
        "## For mod developers",
        "",
        "1. Depend on the Jauml jar for your target Minecraft version and loader.",
        "2. Declare Jauml as a required dependency in `fabric.mod.json` / `mods.toml` / `neoforge.mods.toml`.",
        "3. Optional: call `JaumlConfig.isCompatible(\"2.1.0\")` (or your minimum) during mod init.",
        "",
        "> Public Maven coordinates are not published as a verified NightBeam Maven line in-repo. Use CurseMaven, Modrinth Maven, or a local publish (`local_maven_url`) as your build already does.",
      ].join("\n"),
    },
    {
      slug: "developers",
      title: "For developers",
      sortOrder: 2,
      content: [
        "## Basic open",
        "",
        "```java",
        "import tn.naizo.jauml.api.JaumlConfig;",
        "import tn.naizo.jauml.api.ConfigFile;",
        "",
        "// Opens or creates <configDir>/<subdirectory>/<fileName>.json",
        "ConfigFile config = JaumlConfig.open(\"my_sub_dir\", \"my_config\");",
        "```",
        "",
        "The `.json` extension is added when missing. The same path returns a cached, thread-safe `ConfigFile`.",
        "",
        "## Schema and defaults (2.1.0+)",
        "",
        "```java",
        "import tn.naizo.jauml.api.JaumlConfig;",
        "import tn.naizo.jauml.api.ConfigFile;",
        "import tn.naizo.jauml.api.JsonSchema;",
        "import com.google.gson.JsonObject;",
        "",
        "JsonSchema schema = JsonSchema.parse(\"{\"",
        "    + \"\\\"type\\\":\\\"object\\\",\"",
        "    + \"\\\"properties\\\":{\"",
        "    + \"\\\"enabled\\\":{\\\"type\\\":\\\"boolean\\\"},\"",
        "    + \"\\\"port\\\":{\\\"type\\\":\\\"number\\\"}\"",
        "    + \"}\"",
        "    + \"}\");",
        "",
        "JsonObject defaults = new JsonObject();",
        "defaults.addProperty(\"enabled\", true);",
        "defaults.addProperty(\"port\", 8080);",
        "",
        "ConfigFile config = JaumlConfig.open(\"my_sub_dir\", \"my_config\", schema, defaults);",
        "```",
        "",
        "## Migrations",
        "",
        "Register version-to-version steps with `JsonMigrator`, then open with a target schema version. See [MIGRATION_GUIDE.md](https://github.com/MeherBenSalem/jauml/blob/main/MIGRATION_GUIDE.md) for the full 2.0.0 → 2.1.0 notes (Gson **2.10.x**, Java 17 / 21 / 25).",
        "",
        "## Compatibility helper",
        "",
        "`JaumlConfig.isCompatible(requiredVersion)` requires matching major and `minor >= required` against `LIBRARY_VERSION` (`2.1.1`).",
      ].join("\n"),
    },
    {
      slug: "compatibility",
      title: "Compatibility",
      sortOrder: 3,
      content: [
        "## Loaders and environments",
        "",
        "| Area | Support |",
        "| --- | --- |",
        "| Loaders | Fabric, Forge (notably 1.20.1), NeoForge |",
        "| MultiLoader workspaces | 1.20.1, 1.21.1, 1.21.11, 26.1.2, 26.2 (plus broader listings on CurseForge/Modrinth) |",
        "| Client | Required on Modrinth; Fabric `environment: \"*\"` |",
        "| Dedicated server | Required on Modrinth |",
        "| Gameplay content | None — library only |",
        "",
        "## Runtime dependencies",
        "",
        "Loader/game ranges come from each jar's metadata. JSON work uses **Gson** (documented as 2.10.x for the 2.1.0 series).",
        "",
        "## Known dependents",
        "",
        "Other NightBeam mods (for example RPG Attribute System / Ascendant Mobs trees) may require Jauml. Always trust each project's CurseForge or Modrinth dependency list.",
      ].join("\n"),
    },
    {
      slug: "troubleshooting",
      title: "Troubleshooting",
      sortOrder: 4,
      content: [
        "## `InvalidMixinException` / `MixinMinecraft`",
        "",
        "**Cause:** Older Jauml **1.3.0** jars registered a stub `MixinMinecraft` without a valid `@Mixin` (GitHub issues #3 and #4).",
        "",
        "**Fix:** Replace with the matching **2.1.1** jar for your loader and Minecraft version, then restart.",
        "",
        "## Missing dependency",
        "",
        "**Cause:** A dependent mod requires Jauml, but the jar is missing or the wrong loader/version was installed.",
        "",
        "**Fix:** Install the artifact named for your exact game version and loader, or let the launcher resolve dependencies.",
        "",
        "## Corrupted JSON for a dependent mod",
        "",
        "**Cause:** Malformed JSON or failed validation/migration for a file opened through Jauml.",
        "",
        "**Fix:** Look for a `*.json.bak` beside the config, restore or delete the broken file, and relaunch so defaults can regenerate.",
        "",
        "## Client / server mismatch",
        "",
        "**Cause:** Different Jauml versions or loaders on client vs server.",
        "",
        "**Fix:** Align jars with the pack's Minecraft version on every machine that needs the library.",
      ].join("\n"),
    },
    {
      slug: "faq",
      title: "FAQ",
      sortOrder: 5,
      content: [
        "## Do players need to configure Jauml?",
        "",
        "No. Dependent mods own the JSON files under the config folder.",
        "",
        "## Is Jauml a gameplay mod?",
        "",
        "No. It is a configuration/utility library.",
        "",
        "## Where are config files stored?",
        "",
        "Under the game config directory, in the subdirectory passed to `JaumlConfig.open`, as `*.json` (for example `config/my_sub_dir/my_config.json`).",
        "",
        "## License note",
        "",
        "Jar / Gradle metadata currently declares **MIT**. Checked-in `LICENSE` files use **CC0 1.0** text. Modrinth may show All Rights Reserved. Treat this as an inconsistency until NightBeam publishes one authoritative statement — do not redistribute modified jars without confirmation.",
        "",
        "## Support",
        "",
        "- [GitHub issues](https://github.com/MeherBenSalem/jauml/issues)",
        "- [Discord](https://discord.gg/TJc3CxR4jK)",
        "- [CHANGELOG](https://github.com/MeherBenSalem/jauml/blob/main/CHANGELOG.md)",
      ].join("\n"),
    },
  ],
};
